/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routers/__root'
import { Route as InventoryRouteImport } from './routers/inventory'
import { Route as DiceshockAgentsRouteImport } from './routers/diceshock-agents'
import { Route as ContactUsRouteImport } from './routers/contact-us'
import { Route as IndexRouteImport } from './routers/index'

const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceshockAgentsRoute = DiceshockAgentsRouteImport.update({
  id: '/diceshock-agents',
  path: '/diceshock-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/diceshock-agents': typeof DiceshockAgentsRoute
  '/inventory': typeof InventoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/diceshock-agents': typeof DiceshockAgentsRoute
  '/inventory': typeof InventoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/diceshock-agents': typeof DiceshockAgentsRoute
  '/inventory': typeof InventoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact-us' | '/diceshock-agents' | '/inventory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact-us' | '/diceshock-agents' | '/inventory'
  id: '__root__' | '/' | '/contact-us' | '/diceshock-agents' | '/inventory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactUsRoute: typeof ContactUsRoute
  DiceshockAgentsRoute: typeof DiceshockAgentsRoute
  InventoryRoute: typeof InventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diceshock-agents': {
      id: '/diceshock-agents'
      path: '/diceshock-agents'
      fullPath: '/diceshock-agents'
      preLoaderRoute: typeof DiceshockAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactUsRoute: ContactUsRoute,
  DiceshockAgentsRoute: DiceshockAgentsRoute,
  InventoryRoute: InventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
