// biome-ignore-all lint: gen

/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routers/__root";
import { Route as DashRouteImport } from "./routers/dash";
import { Route as WithHomeLoRouteImport } from "./routers/_with-home-lo";
import { Route as DashIndexRouteImport } from "./routers/dash/index";
import { Route as WithHomeLoIndexRouteImport } from "./routers/_with-home-lo/index";
import { Route as DashUsersRouteImport } from "./routers/dash/users";
import { Route as DashInventoryRouteImport } from "./routers/dash/inventory";
import { Route as DashAcitveRouteImport } from "./routers/dash/acitve";
import { Route as WithHomeLoInventoryRouteImport } from "./routers/_with-home-lo/inventory";
import { Route as WithHomeLoDiceshockAgentsRouteImport } from "./routers/_with-home-lo/diceshock-agents";
import { Route as WithHomeLoContactUsRouteImport } from "./routers/_with-home-lo/contact-us";

const DashRoute = DashRouteImport.update({
  id: "/dash",
  path: "/dash",
  getParentRoute: () => rootRouteImport,
} as any);
const WithHomeLoRoute = WithHomeLoRouteImport.update({
  id: "/_with-home-lo",
  getParentRoute: () => rootRouteImport,
} as any);
const DashIndexRoute = DashIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashRoute,
} as any);
const WithHomeLoIndexRoute = WithHomeLoIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WithHomeLoRoute,
} as any);
const DashUsersRoute = DashUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => DashRoute,
} as any);
const DashInventoryRoute = DashInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => DashRoute,
} as any);
const DashAcitveRoute = DashAcitveRouteImport.update({
  id: "/acitve",
  path: "/acitve",
  getParentRoute: () => DashRoute,
} as any);
const WithHomeLoInventoryRoute = WithHomeLoInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => WithHomeLoRoute,
} as any);
const WithHomeLoDiceshockAgentsRoute =
  WithHomeLoDiceshockAgentsRouteImport.update({
    id: "/diceshock-agents",
    path: "/diceshock-agents",
    getParentRoute: () => WithHomeLoRoute,
  } as any);
const WithHomeLoContactUsRoute = WithHomeLoContactUsRouteImport.update({
  id: "/contact-us",
  path: "/contact-us",
  getParentRoute: () => WithHomeLoRoute,
} as any);

export interface FileRoutesByFullPath {
  "/dash": typeof DashRouteWithChildren;
  "/contact-us": typeof WithHomeLoContactUsRoute;
  "/diceshock-agents": typeof WithHomeLoDiceshockAgentsRoute;
  "/inventory": typeof WithHomeLoInventoryRoute;
  "/dash/acitve": typeof DashAcitveRoute;
  "/dash/inventory": typeof DashInventoryRoute;
  "/dash/users": typeof DashUsersRoute;
  "/": typeof WithHomeLoIndexRoute;
  "/dash/": typeof DashIndexRoute;
}
export interface FileRoutesByTo {
  "/contact-us": typeof WithHomeLoContactUsRoute;
  "/diceshock-agents": typeof WithHomeLoDiceshockAgentsRoute;
  "/inventory": typeof WithHomeLoInventoryRoute;
  "/dash/acitve": typeof DashAcitveRoute;
  "/dash/inventory": typeof DashInventoryRoute;
  "/dash/users": typeof DashUsersRoute;
  "/": typeof WithHomeLoIndexRoute;
  "/dash": typeof DashIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_with-home-lo": typeof WithHomeLoRouteWithChildren;
  "/dash": typeof DashRouteWithChildren;
  "/_with-home-lo/contact-us": typeof WithHomeLoContactUsRoute;
  "/_with-home-lo/diceshock-agents": typeof WithHomeLoDiceshockAgentsRoute;
  "/_with-home-lo/inventory": typeof WithHomeLoInventoryRoute;
  "/dash/acitve": typeof DashAcitveRoute;
  "/dash/inventory": typeof DashInventoryRoute;
  "/dash/users": typeof DashUsersRoute;
  "/_with-home-lo/": typeof WithHomeLoIndexRoute;
  "/dash/": typeof DashIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/dash"
    | "/contact-us"
    | "/diceshock-agents"
    | "/inventory"
    | "/dash/acitve"
    | "/dash/inventory"
    | "/dash/users"
    | "/"
    | "/dash/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/contact-us"
    | "/diceshock-agents"
    | "/inventory"
    | "/dash/acitve"
    | "/dash/inventory"
    | "/dash/users"
    | "/"
    | "/dash";
  id:
    | "__root__"
    | "/_with-home-lo"
    | "/dash"
    | "/_with-home-lo/contact-us"
    | "/_with-home-lo/diceshock-agents"
    | "/_with-home-lo/inventory"
    | "/dash/acitve"
    | "/dash/inventory"
    | "/dash/users"
    | "/_with-home-lo/"
    | "/dash/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  WithHomeLoRoute: typeof WithHomeLoRouteWithChildren;
  DashRoute: typeof DashRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dash": {
      id: "/dash";
      path: "/dash";
      fullPath: "/dash";
      preLoaderRoute: typeof DashRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_with-home-lo": {
      id: "/_with-home-lo";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof WithHomeLoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dash/": {
      id: "/dash/";
      path: "/";
      fullPath: "/dash/";
      preLoaderRoute: typeof DashIndexRouteImport;
      parentRoute: typeof DashRoute;
    };
    "/_with-home-lo/": {
      id: "/_with-home-lo/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof WithHomeLoIndexRouteImport;
      parentRoute: typeof WithHomeLoRoute;
    };
    "/dash/users": {
      id: "/dash/users";
      path: "/users";
      fullPath: "/dash/users";
      preLoaderRoute: typeof DashUsersRouteImport;
      parentRoute: typeof DashRoute;
    };
    "/dash/inventory": {
      id: "/dash/inventory";
      path: "/inventory";
      fullPath: "/dash/inventory";
      preLoaderRoute: typeof DashInventoryRouteImport;
      parentRoute: typeof DashRoute;
    };
    "/dash/acitve": {
      id: "/dash/acitve";
      path: "/acitve";
      fullPath: "/dash/acitve";
      preLoaderRoute: typeof DashAcitveRouteImport;
      parentRoute: typeof DashRoute;
    };
    "/_with-home-lo/inventory": {
      id: "/_with-home-lo/inventory";
      path: "/inventory";
      fullPath: "/inventory";
      preLoaderRoute: typeof WithHomeLoInventoryRouteImport;
      parentRoute: typeof WithHomeLoRoute;
    };
    "/_with-home-lo/diceshock-agents": {
      id: "/_with-home-lo/diceshock-agents";
      path: "/diceshock-agents";
      fullPath: "/diceshock-agents";
      preLoaderRoute: typeof WithHomeLoDiceshockAgentsRouteImport;
      parentRoute: typeof WithHomeLoRoute;
    };
    "/_with-home-lo/contact-us": {
      id: "/_with-home-lo/contact-us";
      path: "/contact-us";
      fullPath: "/contact-us";
      preLoaderRoute: typeof WithHomeLoContactUsRouteImport;
      parentRoute: typeof WithHomeLoRoute;
    };
  }
}

interface WithHomeLoRouteChildren {
  WithHomeLoContactUsRoute: typeof WithHomeLoContactUsRoute;
  WithHomeLoDiceshockAgentsRoute: typeof WithHomeLoDiceshockAgentsRoute;
  WithHomeLoInventoryRoute: typeof WithHomeLoInventoryRoute;
  WithHomeLoIndexRoute: typeof WithHomeLoIndexRoute;
}

const WithHomeLoRouteChildren: WithHomeLoRouteChildren = {
  WithHomeLoContactUsRoute: WithHomeLoContactUsRoute,
  WithHomeLoDiceshockAgentsRoute: WithHomeLoDiceshockAgentsRoute,
  WithHomeLoInventoryRoute: WithHomeLoInventoryRoute,
  WithHomeLoIndexRoute: WithHomeLoIndexRoute,
};

const WithHomeLoRouteWithChildren = WithHomeLoRoute._addFileChildren(
  WithHomeLoRouteChildren,
);

interface DashRouteChildren {
  DashAcitveRoute: typeof DashAcitveRoute;
  DashInventoryRoute: typeof DashInventoryRoute;
  DashUsersRoute: typeof DashUsersRoute;
  DashIndexRoute: typeof DashIndexRoute;
}

const DashRouteChildren: DashRouteChildren = {
  DashAcitveRoute: DashAcitveRoute,
  DashInventoryRoute: DashInventoryRoute,
  DashUsersRoute: DashUsersRoute,
  DashIndexRoute: DashIndexRoute,
};

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  WithHomeLoRoute: WithHomeLoRouteWithChildren,
  DashRoute: DashRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
