// biome-ignore-all lint: gen

/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routers/__root'
import { Route as TRouteImport } from './routers/t'
import { Route as ReadyRouteImport } from './routers/ready'
import { Route as MyRiichiRouteImport } from './routers/my-riichi'
import { Route as DashRouteImport } from './routers/dash'
import { Route as WithHomeLoRouteImport } from './routers/_with-home-lo'
import { Route as DashIndexRouteImport } from './routers/dash/index'
import { Route as WithHomeLoIndexRouteImport } from './routers/_with-home-lo/index'
import { Route as TCodeRouteImport } from './routers/t/$code'
import { Route as ReadyCodeRouteImport } from './routers/ready/$code'
import { Route as MyRiichiIdRouteImport } from './routers/my-riichi/$id'
import { Route as DashUsersRouteImport } from './routers/dash/users'
import { Route as DashTablesRouteImport } from './routers/dash/tables'
import { Route as DashPricingRouteImport } from './routers/dash/pricing'
import { Route as DashOrdersRouteImport } from './routers/dash/orders'
import { Route as DashMediaRouteImport } from './routers/dash/media'
import { Route as DashGszRouteImport } from './routers/dash/gsz'
import { Route as DashEventsRouteImport } from './routers/dash/events'
import { Route as DashActivesRouteImport } from './routers/dash/actives'
import { Route as WithHomeLoRiichiRouteImport } from './routers/_with-home-lo/riichi'
import { Route as WithHomeLoMeRouteImport } from './routers/_with-home-lo/me'
import { Route as WithHomeLoInventoryRouteImport } from './routers/_with-home-lo/inventory'
import { Route as WithHomeLoExternalRedirectRouteImport } from './routers/_with-home-lo/external-redirect'
import { Route as WithHomeLoDiceshockAgentsRouteImport } from './routers/_with-home-lo/diceshock-agents'
import { Route as WithHomeLoContactUsRouteImport } from './routers/_with-home-lo/contact-us'
import { Route as WithHomeLoActivesRouteImport } from './routers/_with-home-lo/actives'
import { Route as DashUsersIdRouteImport } from './routers/dash/users_.$id'
import { Route as DashTablesIdRouteImport } from './routers/dash/tables_.$id'
import { Route as DashPricingIdRouteImport } from './routers/dash/pricing_.$id'
import { Route as DashOrdersSettleRouteImport } from './routers/dash/orders_.settle'
import { Route as DashGszIdRouteImport } from './routers/dash/gsz_.$id'
import { Route as DashEventsIdRouteImport } from './routers/dash/events_.$id'
import { Route as DashActivesIdRouteImport } from './routers/dash/actives_.$id'
import { Route as WithHomeLoInventoryIdRouteImport } from './routers/_with-home-lo/inventory_.$id'
import { Route as WithHomeLoEventsIdRouteImport } from './routers/_with-home-lo/events_.$id'
import { Route as WithHomeLoActivesNewRouteImport } from './routers/_with-home-lo/actives_.new'
import { Route as WithHomeLoActivesIdRouteImport } from './routers/_with-home-lo/actives_.$id'
import { Route as DashOrdersIdSettleRouteImport } from './routers/dash/orders_.$id.settle'

const TRoute = TRouteImport.update({
  id: '/t',
  path: '/t',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRiichiRoute = MyRiichiRouteImport.update({
  id: '/my-riichi',
  path: '/my-riichi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const WithHomeLoRoute = WithHomeLoRouteImport.update({
  id: '/_with-home-lo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const WithHomeLoIndexRoute = WithHomeLoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => TRoute,
} as any)
const ReadyCodeRoute = ReadyCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ReadyRoute,
} as any)
const MyRiichiIdRoute = MyRiichiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyRiichiRoute,
} as any)
const DashUsersRoute = DashUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashRoute,
} as any)
const DashTablesRoute = DashTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashRoute,
} as any)
const DashPricingRoute = DashPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashRoute,
} as any)
const DashOrdersRoute = DashOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashRoute,
} as any)
const DashMediaRoute = DashMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashRoute,
} as any)
const DashGszRoute = DashGszRouteImport.update({
  id: '/gsz',
  path: '/gsz',
  getParentRoute: () => DashRoute,
} as any)
const DashEventsRoute = DashEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashRoute,
} as any)
const DashActivesRoute = DashActivesRouteImport.update({
  id: '/actives',
  path: '/actives',
  getParentRoute: () => DashRoute,
} as any)
const WithHomeLoRiichiRoute = WithHomeLoRiichiRouteImport.update({
  id: '/riichi',
  path: '/riichi',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const WithHomeLoMeRoute = WithHomeLoMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const WithHomeLoInventoryRoute = WithHomeLoInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const WithHomeLoExternalRedirectRoute =
  WithHomeLoExternalRedirectRouteImport.update({
    id: '/external-redirect',
    path: '/external-redirect',
    getParentRoute: () => WithHomeLoRoute,
  } as any)
const WithHomeLoDiceshockAgentsRoute =
  WithHomeLoDiceshockAgentsRouteImport.update({
    id: '/diceshock-agents',
    path: '/diceshock-agents',
    getParentRoute: () => WithHomeLoRoute,
  } as any)
const WithHomeLoContactUsRoute = WithHomeLoContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const WithHomeLoActivesRoute = WithHomeLoActivesRouteImport.update({
  id: '/actives',
  path: '/actives',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const DashUsersIdRoute = DashUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashTablesIdRoute = DashTablesIdRouteImport.update({
  id: '/tables_/$id',
  path: '/tables/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashPricingIdRoute = DashPricingIdRouteImport.update({
  id: '/pricing_/$id',
  path: '/pricing/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashOrdersSettleRoute = DashOrdersSettleRouteImport.update({
  id: '/orders_/settle',
  path: '/orders/settle',
  getParentRoute: () => DashRoute,
} as any)
const DashGszIdRoute = DashGszIdRouteImport.update({
  id: '/gsz_/$id',
  path: '/gsz/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashEventsIdRoute = DashEventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => DashRoute,
} as any)
const DashActivesIdRoute = DashActivesIdRouteImport.update({
  id: '/actives_/$id',
  path: '/actives/$id',
  getParentRoute: () => DashRoute,
} as any)
const WithHomeLoInventoryIdRoute = WithHomeLoInventoryIdRouteImport.update({
  id: '/inventory_/$id',
  path: '/inventory/$id',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const WithHomeLoEventsIdRoute = WithHomeLoEventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const WithHomeLoActivesNewRoute = WithHomeLoActivesNewRouteImport.update({
  id: '/actives_/new',
  path: '/actives/new',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const WithHomeLoActivesIdRoute = WithHomeLoActivesIdRouteImport.update({
  id: '/actives_/$id',
  path: '/actives/$id',
  getParentRoute: () => WithHomeLoRoute,
} as any)
const DashOrdersIdSettleRoute = DashOrdersIdSettleRouteImport.update({
  id: '/orders_/$id/settle',
  path: '/orders/$id/settle',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WithHomeLoIndexRoute
  '/dash': typeof DashRouteWithChildren
  '/my-riichi': typeof MyRiichiRouteWithChildren
  '/ready': typeof ReadyRouteWithChildren
  '/t': typeof TRouteWithChildren
  '/actives': typeof WithHomeLoActivesRoute
  '/contact-us': typeof WithHomeLoContactUsRoute
  '/diceshock-agents': typeof WithHomeLoDiceshockAgentsRoute
  '/external-redirect': typeof WithHomeLoExternalRedirectRoute
  '/inventory': typeof WithHomeLoInventoryRoute
  '/me': typeof WithHomeLoMeRoute
  '/riichi': typeof WithHomeLoRiichiRoute
  '/dash/actives': typeof DashActivesRoute
  '/dash/events': typeof DashEventsRoute
  '/dash/gsz': typeof DashGszRoute
  '/dash/media': typeof DashMediaRoute
  '/dash/orders': typeof DashOrdersRoute
  '/dash/pricing': typeof DashPricingRoute
  '/dash/tables': typeof DashTablesRoute
  '/dash/users': typeof DashUsersRoute
  '/my-riichi/$id': typeof MyRiichiIdRoute
  '/ready/$code': typeof ReadyCodeRoute
  '/t/$code': typeof TCodeRoute
  '/dash/': typeof DashIndexRoute
  '/actives/$id': typeof WithHomeLoActivesIdRoute
  '/actives/new': typeof WithHomeLoActivesNewRoute
  '/events/$id': typeof WithHomeLoEventsIdRoute
  '/inventory/$id': typeof WithHomeLoInventoryIdRoute
  '/dash/actives/$id': typeof DashActivesIdRoute
  '/dash/events/$id': typeof DashEventsIdRoute
  '/dash/gsz/$id': typeof DashGszIdRoute
  '/dash/orders/settle': typeof DashOrdersSettleRoute
  '/dash/pricing/$id': typeof DashPricingIdRoute
  '/dash/tables/$id': typeof DashTablesIdRoute
  '/dash/users/$id': typeof DashUsersIdRoute
  '/dash/orders/$id/settle': typeof DashOrdersIdSettleRoute
}
export interface FileRoutesByTo {
  '/my-riichi': typeof MyRiichiRouteWithChildren
  '/ready': typeof ReadyRouteWithChildren
  '/t': typeof TRouteWithChildren
  '/actives': typeof WithHomeLoActivesRoute
  '/contact-us': typeof WithHomeLoContactUsRoute
  '/diceshock-agents': typeof WithHomeLoDiceshockAgentsRoute
  '/external-redirect': typeof WithHomeLoExternalRedirectRoute
  '/inventory': typeof WithHomeLoInventoryRoute
  '/me': typeof WithHomeLoMeRoute
  '/riichi': typeof WithHomeLoRiichiRoute
  '/dash/actives': typeof DashActivesRoute
  '/dash/events': typeof DashEventsRoute
  '/dash/gsz': typeof DashGszRoute
  '/dash/media': typeof DashMediaRoute
  '/dash/orders': typeof DashOrdersRoute
  '/dash/pricing': typeof DashPricingRoute
  '/dash/tables': typeof DashTablesRoute
  '/dash/users': typeof DashUsersRoute
  '/my-riichi/$id': typeof MyRiichiIdRoute
  '/ready/$code': typeof ReadyCodeRoute
  '/t/$code': typeof TCodeRoute
  '/': typeof WithHomeLoIndexRoute
  '/dash': typeof DashIndexRoute
  '/actives/$id': typeof WithHomeLoActivesIdRoute
  '/actives/new': typeof WithHomeLoActivesNewRoute
  '/events/$id': typeof WithHomeLoEventsIdRoute
  '/inventory/$id': typeof WithHomeLoInventoryIdRoute
  '/dash/actives/$id': typeof DashActivesIdRoute
  '/dash/events/$id': typeof DashEventsIdRoute
  '/dash/gsz/$id': typeof DashGszIdRoute
  '/dash/orders/settle': typeof DashOrdersSettleRoute
  '/dash/pricing/$id': typeof DashPricingIdRoute
  '/dash/tables/$id': typeof DashTablesIdRoute
  '/dash/users/$id': typeof DashUsersIdRoute
  '/dash/orders/$id/settle': typeof DashOrdersIdSettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_with-home-lo': typeof WithHomeLoRouteWithChildren
  '/dash': typeof DashRouteWithChildren
  '/my-riichi': typeof MyRiichiRouteWithChildren
  '/ready': typeof ReadyRouteWithChildren
  '/t': typeof TRouteWithChildren
  '/_with-home-lo/actives': typeof WithHomeLoActivesRoute
  '/_with-home-lo/contact-us': typeof WithHomeLoContactUsRoute
  '/_with-home-lo/diceshock-agents': typeof WithHomeLoDiceshockAgentsRoute
  '/_with-home-lo/external-redirect': typeof WithHomeLoExternalRedirectRoute
  '/_with-home-lo/inventory': typeof WithHomeLoInventoryRoute
  '/_with-home-lo/me': typeof WithHomeLoMeRoute
  '/_with-home-lo/riichi': typeof WithHomeLoRiichiRoute
  '/dash/actives': typeof DashActivesRoute
  '/dash/events': typeof DashEventsRoute
  '/dash/gsz': typeof DashGszRoute
  '/dash/media': typeof DashMediaRoute
  '/dash/orders': typeof DashOrdersRoute
  '/dash/pricing': typeof DashPricingRoute
  '/dash/tables': typeof DashTablesRoute
  '/dash/users': typeof DashUsersRoute
  '/my-riichi/$id': typeof MyRiichiIdRoute
  '/ready/$code': typeof ReadyCodeRoute
  '/t/$code': typeof TCodeRoute
  '/_with-home-lo/': typeof WithHomeLoIndexRoute
  '/dash/': typeof DashIndexRoute
  '/_with-home-lo/actives_/$id': typeof WithHomeLoActivesIdRoute
  '/_with-home-lo/actives_/new': typeof WithHomeLoActivesNewRoute
  '/_with-home-lo/events_/$id': typeof WithHomeLoEventsIdRoute
  '/_with-home-lo/inventory_/$id': typeof WithHomeLoInventoryIdRoute
  '/dash/actives_/$id': typeof DashActivesIdRoute
  '/dash/events_/$id': typeof DashEventsIdRoute
  '/dash/gsz_/$id': typeof DashGszIdRoute
  '/dash/orders_/settle': typeof DashOrdersSettleRoute
  '/dash/pricing_/$id': typeof DashPricingIdRoute
  '/dash/tables_/$id': typeof DashTablesIdRoute
  '/dash/users_/$id': typeof DashUsersIdRoute
  '/dash/orders_/$id/settle': typeof DashOrdersIdSettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/my-riichi'
    | '/ready'
    | '/t'
    | '/actives'
    | '/contact-us'
    | '/diceshock-agents'
    | '/external-redirect'
    | '/inventory'
    | '/me'
    | '/riichi'
    | '/dash/actives'
    | '/dash/events'
    | '/dash/gsz'
    | '/dash/media'
    | '/dash/orders'
    | '/dash/pricing'
    | '/dash/tables'
    | '/dash/users'
    | '/my-riichi/$id'
    | '/ready/$code'
    | '/t/$code'
    | '/dash/'
    | '/actives/$id'
    | '/actives/new'
    | '/events/$id'
    | '/inventory/$id'
    | '/dash/actives/$id'
    | '/dash/events/$id'
    | '/dash/gsz/$id'
    | '/dash/orders/settle'
    | '/dash/pricing/$id'
    | '/dash/tables/$id'
    | '/dash/users/$id'
    | '/dash/orders/$id/settle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/my-riichi'
    | '/ready'
    | '/t'
    | '/actives'
    | '/contact-us'
    | '/diceshock-agents'
    | '/external-redirect'
    | '/inventory'
    | '/me'
    | '/riichi'
    | '/dash/actives'
    | '/dash/events'
    | '/dash/gsz'
    | '/dash/media'
    | '/dash/orders'
    | '/dash/pricing'
    | '/dash/tables'
    | '/dash/users'
    | '/my-riichi/$id'
    | '/ready/$code'
    | '/t/$code'
    | '/'
    | '/dash'
    | '/actives/$id'
    | '/actives/new'
    | '/events/$id'
    | '/inventory/$id'
    | '/dash/actives/$id'
    | '/dash/events/$id'
    | '/dash/gsz/$id'
    | '/dash/orders/settle'
    | '/dash/pricing/$id'
    | '/dash/tables/$id'
    | '/dash/users/$id'
    | '/dash/orders/$id/settle'
  id:
    | '__root__'
    | '/_with-home-lo'
    | '/dash'
    | '/my-riichi'
    | '/ready'
    | '/t'
    | '/_with-home-lo/actives'
    | '/_with-home-lo/contact-us'
    | '/_with-home-lo/diceshock-agents'
    | '/_with-home-lo/external-redirect'
    | '/_with-home-lo/inventory'
    | '/_with-home-lo/me'
    | '/_with-home-lo/riichi'
    | '/dash/actives'
    | '/dash/events'
    | '/dash/gsz'
    | '/dash/media'
    | '/dash/orders'
    | '/dash/pricing'
    | '/dash/tables'
    | '/dash/users'
    | '/my-riichi/$id'
    | '/ready/$code'
    | '/t/$code'
    | '/_with-home-lo/'
    | '/dash/'
    | '/_with-home-lo/actives_/$id'
    | '/_with-home-lo/actives_/new'
    | '/_with-home-lo/events_/$id'
    | '/_with-home-lo/inventory_/$id'
    | '/dash/actives_/$id'
    | '/dash/events_/$id'
    | '/dash/gsz_/$id'
    | '/dash/orders_/settle'
    | '/dash/pricing_/$id'
    | '/dash/tables_/$id'
    | '/dash/users_/$id'
    | '/dash/orders_/$id/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithHomeLoRoute: typeof WithHomeLoRouteWithChildren
  DashRoute: typeof DashRouteWithChildren
  MyRiichiRoute: typeof MyRiichiRouteWithChildren
  ReadyRoute: typeof ReadyRouteWithChildren
  TRoute: typeof TRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/t': {
      id: '/t'
      path: '/t'
      fullPath: '/t'
      preLoaderRoute: typeof TRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-riichi': {
      id: '/my-riichi'
      path: '/my-riichi'
      fullPath: '/my-riichi'
      preLoaderRoute: typeof MyRiichiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-home-lo': {
      id: '/_with-home-lo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithHomeLoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_with-home-lo/': {
      id: '/_with-home-lo/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithHomeLoIndexRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof TRoute
    }
    '/ready/$code': {
      id: '/ready/$code'
      path: '/$code'
      fullPath: '/ready/$code'
      preLoaderRoute: typeof ReadyCodeRouteImport
      parentRoute: typeof ReadyRoute
    }
    '/my-riichi/$id': {
      id: '/my-riichi/$id'
      path: '/$id'
      fullPath: '/my-riichi/$id'
      preLoaderRoute: typeof MyRiichiIdRouteImport
      parentRoute: typeof MyRiichiRoute
    }
    '/dash/users': {
      id: '/dash/users'
      path: '/users'
      fullPath: '/dash/users'
      preLoaderRoute: typeof DashUsersRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/tables': {
      id: '/dash/tables'
      path: '/tables'
      fullPath: '/dash/tables'
      preLoaderRoute: typeof DashTablesRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/pricing': {
      id: '/dash/pricing'
      path: '/pricing'
      fullPath: '/dash/pricing'
      preLoaderRoute: typeof DashPricingRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/orders': {
      id: '/dash/orders'
      path: '/orders'
      fullPath: '/dash/orders'
      preLoaderRoute: typeof DashOrdersRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/media': {
      id: '/dash/media'
      path: '/media'
      fullPath: '/dash/media'
      preLoaderRoute: typeof DashMediaRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/gsz': {
      id: '/dash/gsz'
      path: '/gsz'
      fullPath: '/dash/gsz'
      preLoaderRoute: typeof DashGszRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/events': {
      id: '/dash/events'
      path: '/events'
      fullPath: '/dash/events'
      preLoaderRoute: typeof DashEventsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/actives': {
      id: '/dash/actives'
      path: '/actives'
      fullPath: '/dash/actives'
      preLoaderRoute: typeof DashActivesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_with-home-lo/riichi': {
      id: '/_with-home-lo/riichi'
      path: '/riichi'
      fullPath: '/riichi'
      preLoaderRoute: typeof WithHomeLoRiichiRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/me': {
      id: '/_with-home-lo/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof WithHomeLoMeRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/inventory': {
      id: '/_with-home-lo/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof WithHomeLoInventoryRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/external-redirect': {
      id: '/_with-home-lo/external-redirect'
      path: '/external-redirect'
      fullPath: '/external-redirect'
      preLoaderRoute: typeof WithHomeLoExternalRedirectRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/diceshock-agents': {
      id: '/_with-home-lo/diceshock-agents'
      path: '/diceshock-agents'
      fullPath: '/diceshock-agents'
      preLoaderRoute: typeof WithHomeLoDiceshockAgentsRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/contact-us': {
      id: '/_with-home-lo/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof WithHomeLoContactUsRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/actives': {
      id: '/_with-home-lo/actives'
      path: '/actives'
      fullPath: '/actives'
      preLoaderRoute: typeof WithHomeLoActivesRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/dash/users_/$id': {
      id: '/dash/users_/$id'
      path: '/users/$id'
      fullPath: '/dash/users/$id'
      preLoaderRoute: typeof DashUsersIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/tables_/$id': {
      id: '/dash/tables_/$id'
      path: '/tables/$id'
      fullPath: '/dash/tables/$id'
      preLoaderRoute: typeof DashTablesIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/pricing_/$id': {
      id: '/dash/pricing_/$id'
      path: '/pricing/$id'
      fullPath: '/dash/pricing/$id'
      preLoaderRoute: typeof DashPricingIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/orders_/settle': {
      id: '/dash/orders_/settle'
      path: '/orders/settle'
      fullPath: '/dash/orders/settle'
      preLoaderRoute: typeof DashOrdersSettleRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/gsz_/$id': {
      id: '/dash/gsz_/$id'
      path: '/gsz/$id'
      fullPath: '/dash/gsz/$id'
      preLoaderRoute: typeof DashGszIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/events_/$id': {
      id: '/dash/events_/$id'
      path: '/events/$id'
      fullPath: '/dash/events/$id'
      preLoaderRoute: typeof DashEventsIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/actives_/$id': {
      id: '/dash/actives_/$id'
      path: '/actives/$id'
      fullPath: '/dash/actives/$id'
      preLoaderRoute: typeof DashActivesIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/_with-home-lo/inventory_/$id': {
      id: '/_with-home-lo/inventory_/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof WithHomeLoInventoryIdRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/events_/$id': {
      id: '/_with-home-lo/events_/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof WithHomeLoEventsIdRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/actives_/new': {
      id: '/_with-home-lo/actives_/new'
      path: '/actives/new'
      fullPath: '/actives/new'
      preLoaderRoute: typeof WithHomeLoActivesNewRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/_with-home-lo/actives_/$id': {
      id: '/_with-home-lo/actives_/$id'
      path: '/actives/$id'
      fullPath: '/actives/$id'
      preLoaderRoute: typeof WithHomeLoActivesIdRouteImport
      parentRoute: typeof WithHomeLoRoute
    }
    '/dash/orders_/$id/settle': {
      id: '/dash/orders_/$id/settle'
      path: '/orders/$id/settle'
      fullPath: '/dash/orders/$id/settle'
      preLoaderRoute: typeof DashOrdersIdSettleRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface WithHomeLoRouteChildren {
  WithHomeLoActivesRoute: typeof WithHomeLoActivesRoute
  WithHomeLoContactUsRoute: typeof WithHomeLoContactUsRoute
  WithHomeLoDiceshockAgentsRoute: typeof WithHomeLoDiceshockAgentsRoute
  WithHomeLoExternalRedirectRoute: typeof WithHomeLoExternalRedirectRoute
  WithHomeLoInventoryRoute: typeof WithHomeLoInventoryRoute
  WithHomeLoMeRoute: typeof WithHomeLoMeRoute
  WithHomeLoRiichiRoute: typeof WithHomeLoRiichiRoute
  WithHomeLoIndexRoute: typeof WithHomeLoIndexRoute
  WithHomeLoActivesIdRoute: typeof WithHomeLoActivesIdRoute
  WithHomeLoActivesNewRoute: typeof WithHomeLoActivesNewRoute
  WithHomeLoEventsIdRoute: typeof WithHomeLoEventsIdRoute
  WithHomeLoInventoryIdRoute: typeof WithHomeLoInventoryIdRoute
}

const WithHomeLoRouteChildren: WithHomeLoRouteChildren = {
  WithHomeLoActivesRoute: WithHomeLoActivesRoute,
  WithHomeLoContactUsRoute: WithHomeLoContactUsRoute,
  WithHomeLoDiceshockAgentsRoute: WithHomeLoDiceshockAgentsRoute,
  WithHomeLoExternalRedirectRoute: WithHomeLoExternalRedirectRoute,
  WithHomeLoInventoryRoute: WithHomeLoInventoryRoute,
  WithHomeLoMeRoute: WithHomeLoMeRoute,
  WithHomeLoRiichiRoute: WithHomeLoRiichiRoute,
  WithHomeLoIndexRoute: WithHomeLoIndexRoute,
  WithHomeLoActivesIdRoute: WithHomeLoActivesIdRoute,
  WithHomeLoActivesNewRoute: WithHomeLoActivesNewRoute,
  WithHomeLoEventsIdRoute: WithHomeLoEventsIdRoute,
  WithHomeLoInventoryIdRoute: WithHomeLoInventoryIdRoute,
}

const WithHomeLoRouteWithChildren = WithHomeLoRoute._addFileChildren(
  WithHomeLoRouteChildren,
)

interface DashRouteChildren {
  DashActivesRoute: typeof DashActivesRoute
  DashEventsRoute: typeof DashEventsRoute
  DashGszRoute: typeof DashGszRoute
  DashMediaRoute: typeof DashMediaRoute
  DashOrdersRoute: typeof DashOrdersRoute
  DashPricingRoute: typeof DashPricingRoute
  DashTablesRoute: typeof DashTablesRoute
  DashUsersRoute: typeof DashUsersRoute
  DashIndexRoute: typeof DashIndexRoute
  DashActivesIdRoute: typeof DashActivesIdRoute
  DashEventsIdRoute: typeof DashEventsIdRoute
  DashGszIdRoute: typeof DashGszIdRoute
  DashOrdersSettleRoute: typeof DashOrdersSettleRoute
  DashPricingIdRoute: typeof DashPricingIdRoute
  DashTablesIdRoute: typeof DashTablesIdRoute
  DashUsersIdRoute: typeof DashUsersIdRoute
  DashOrdersIdSettleRoute: typeof DashOrdersIdSettleRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashActivesRoute: DashActivesRoute,
  DashEventsRoute: DashEventsRoute,
  DashGszRoute: DashGszRoute,
  DashMediaRoute: DashMediaRoute,
  DashOrdersRoute: DashOrdersRoute,
  DashPricingRoute: DashPricingRoute,
  DashTablesRoute: DashTablesRoute,
  DashUsersRoute: DashUsersRoute,
  DashIndexRoute: DashIndexRoute,
  DashActivesIdRoute: DashActivesIdRoute,
  DashEventsIdRoute: DashEventsIdRoute,
  DashGszIdRoute: DashGszIdRoute,
  DashOrdersSettleRoute: DashOrdersSettleRoute,
  DashPricingIdRoute: DashPricingIdRoute,
  DashTablesIdRoute: DashTablesIdRoute,
  DashUsersIdRoute: DashUsersIdRoute,
  DashOrdersIdSettleRoute: DashOrdersIdSettleRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface MyRiichiRouteChildren {
  MyRiichiIdRoute: typeof MyRiichiIdRoute
}

const MyRiichiRouteChildren: MyRiichiRouteChildren = {
  MyRiichiIdRoute: MyRiichiIdRoute,
}

const MyRiichiRouteWithChildren = MyRiichiRoute._addFileChildren(
  MyRiichiRouteChildren,
)

interface ReadyRouteChildren {
  ReadyCodeRoute: typeof ReadyCodeRoute
}

const ReadyRouteChildren: ReadyRouteChildren = {
  ReadyCodeRoute: ReadyCodeRoute,
}

const ReadyRouteWithChildren = ReadyRoute._addFileChildren(ReadyRouteChildren)

interface TRouteChildren {
  TCodeRoute: typeof TCodeRoute
}

const TRouteChildren: TRouteChildren = {
  TCodeRoute: TCodeRoute,
}

const TRouteWithChildren = TRoute._addFileChildren(TRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WithHomeLoRoute: WithHomeLoRouteWithChildren,
  DashRoute: DashRouteWithChildren,
  MyRiichiRoute: MyRiichiRouteWithChildren,
  ReadyRoute: ReadyRouteWithChildren,
  TRoute: TRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
