// biome-ignore-all lint: gen

/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routers/__root'
import { Route as TRouteImport } from './routers/t'
import { Route as ReadyRouteImport } from './routers/ready'
import { Route as MyRiichiRouteImport } from './routers/my-riichi'
import { Route as DashRouteImport } from './routers/dash'
import { Route as StoreRouteImport } from './routers/$store'
import { Route as IndexRouteImport } from './routers/index'
import { Route as DashIndexRouteImport } from './routers/dash/index'
import { Route as TCodeRouteImport } from './routers/t/$code'
import { Route as ReadyCodeRouteImport } from './routers/ready/$code'
import { Route as MyRiichiIdRouteImport } from './routers/my-riichi/$id'
import { Route as DashStoreRouteImport } from './routers/dash/$store'
import { Route as StoreWithHomeLoRouteImport } from './routers/$store/_with-home-lo'
import { Route as DashStoreIndexRouteImport } from './routers/dash/$store/index'
import { Route as StoreWithHomeLoIndexRouteImport } from './routers/$store/_with-home-lo/index'
import { Route as DashStoreUsersRouteImport } from './routers/dash/$store/users'
import { Route as DashStoreTablesRouteImport } from './routers/dash/$store/tables'
import { Route as DashStorePricingRouteImport } from './routers/dash/$store/pricing'
import { Route as DashStoreOrdersRouteImport } from './routers/dash/$store/orders'
import { Route as DashStoreMediaRouteImport } from './routers/dash/$store/media'
import { Route as DashStoreGszRouteImport } from './routers/dash/$store/gsz'
import { Route as DashStoreEventsRouteImport } from './routers/dash/$store/events'
import { Route as DashStoreActivesRouteImport } from './routers/dash/$store/actives'
import { Route as StoreWithHomeLoRiichiRouteImport } from './routers/$store/_with-home-lo/riichi'
import { Route as StoreWithHomeLoMeRouteImport } from './routers/$store/_with-home-lo/me'
import { Route as StoreWithHomeLoInventoryRouteImport } from './routers/$store/_with-home-lo/inventory'
import { Route as StoreWithHomeLoExternalRedirectRouteImport } from './routers/$store/_with-home-lo/external-redirect'
import { Route as StoreWithHomeLoDiceshockAgentsRouteImport } from './routers/$store/_with-home-lo/diceshock-agents'
import { Route as StoreWithHomeLoContactUsRouteImport } from './routers/$store/_with-home-lo/contact-us'
import { Route as StoreWithHomeLoActivesRouteImport } from './routers/$store/_with-home-lo/actives'
import { Route as DashStoreUsersIdRouteImport } from './routers/dash/$store/users_.$id'
import { Route as DashStoreTablesIdRouteImport } from './routers/dash/$store/tables_.$id'
import { Route as DashStorePricingIdRouteImport } from './routers/dash/$store/pricing_.$id'
import { Route as DashStoreOrdersSettleRouteImport } from './routers/dash/$store/orders_.settle'
import { Route as DashStoreGszIdRouteImport } from './routers/dash/$store/gsz_.$id'
import { Route as DashStoreEventsIdRouteImport } from './routers/dash/$store/events_.$id'
import { Route as DashStoreActivesIdRouteImport } from './routers/dash/$store/actives_.$id'
import { Route as StoreWithHomeLoInventoryIdRouteImport } from './routers/$store/_with-home-lo/inventory_.$id'
import { Route as StoreWithHomeLoEventsIdRouteImport } from './routers/$store/_with-home-lo/events_.$id'
import { Route as StoreWithHomeLoActivesNewRouteImport } from './routers/$store/_with-home-lo/actives_.new'
import { Route as StoreWithHomeLoActivesIdRouteImport } from './routers/$store/_with-home-lo/actives_.$id'
import { Route as DashStoreOrdersIdSettleRouteImport } from './routers/dash/$store/orders_.$id.settle'

const TRoute = TRouteImport.update({
  id: '/t',
  path: '/t',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRiichiRoute = MyRiichiRouteImport.update({
  id: '/my-riichi',
  path: '/my-riichi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/$store',
  path: '/$store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => TRoute,
} as any)
const ReadyCodeRoute = ReadyCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ReadyRoute,
} as any)
const MyRiichiIdRoute = MyRiichiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyRiichiRoute,
} as any)
const DashStoreRoute = DashStoreRouteImport.update({
  id: '/$store',
  path: '/$store',
  getParentRoute: () => DashRoute,
} as any)
const StoreWithHomeLoRoute = StoreWithHomeLoRouteImport.update({
  id: '/_with-home-lo',
  getParentRoute: () => StoreRoute,
} as any)
const DashStoreIndexRoute = DashStoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashStoreRoute,
} as any)
const StoreWithHomeLoIndexRoute = StoreWithHomeLoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreWithHomeLoRoute,
} as any)
const DashStoreUsersRoute = DashStoreUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreTablesRoute = DashStoreTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStorePricingRoute = DashStorePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreOrdersRoute = DashStoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreMediaRoute = DashStoreMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreGszRoute = DashStoreGszRouteImport.update({
  id: '/gsz',
  path: '/gsz',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreEventsRoute = DashStoreEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreActivesRoute = DashStoreActivesRouteImport.update({
  id: '/actives',
  path: '/actives',
  getParentRoute: () => DashStoreRoute,
} as any)
const StoreWithHomeLoRiichiRoute = StoreWithHomeLoRiichiRouteImport.update({
  id: '/riichi',
  path: '/riichi',
  getParentRoute: () => StoreWithHomeLoRoute,
} as any)
const StoreWithHomeLoMeRoute = StoreWithHomeLoMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => StoreWithHomeLoRoute,
} as any)
const StoreWithHomeLoInventoryRoute =
  StoreWithHomeLoInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => StoreWithHomeLoRoute,
  } as any)
const StoreWithHomeLoExternalRedirectRoute =
  StoreWithHomeLoExternalRedirectRouteImport.update({
    id: '/external-redirect',
    path: '/external-redirect',
    getParentRoute: () => StoreWithHomeLoRoute,
  } as any)
const StoreWithHomeLoDiceshockAgentsRoute =
  StoreWithHomeLoDiceshockAgentsRouteImport.update({
    id: '/diceshock-agents',
    path: '/diceshock-agents',
    getParentRoute: () => StoreWithHomeLoRoute,
  } as any)
const StoreWithHomeLoContactUsRoute =
  StoreWithHomeLoContactUsRouteImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => StoreWithHomeLoRoute,
  } as any)
const StoreWithHomeLoActivesRoute = StoreWithHomeLoActivesRouteImport.update({
  id: '/actives',
  path: '/actives',
  getParentRoute: () => StoreWithHomeLoRoute,
} as any)
const DashStoreUsersIdRoute = DashStoreUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreTablesIdRoute = DashStoreTablesIdRouteImport.update({
  id: '/tables_/$id',
  path: '/tables/$id',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStorePricingIdRoute = DashStorePricingIdRouteImport.update({
  id: '/pricing_/$id',
  path: '/pricing/$id',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreOrdersSettleRoute = DashStoreOrdersSettleRouteImport.update({
  id: '/orders_/settle',
  path: '/orders/settle',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreGszIdRoute = DashStoreGszIdRouteImport.update({
  id: '/gsz_/$id',
  path: '/gsz/$id',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreEventsIdRoute = DashStoreEventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => DashStoreRoute,
} as any)
const DashStoreActivesIdRoute = DashStoreActivesIdRouteImport.update({
  id: '/actives_/$id',
  path: '/actives/$id',
  getParentRoute: () => DashStoreRoute,
} as any)
const StoreWithHomeLoInventoryIdRoute =
  StoreWithHomeLoInventoryIdRouteImport.update({
    id: '/inventory_/$id',
    path: '/inventory/$id',
    getParentRoute: () => StoreWithHomeLoRoute,
  } as any)
const StoreWithHomeLoEventsIdRoute = StoreWithHomeLoEventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => StoreWithHomeLoRoute,
} as any)
const StoreWithHomeLoActivesNewRoute =
  StoreWithHomeLoActivesNewRouteImport.update({
    id: '/actives_/new',
    path: '/actives/new',
    getParentRoute: () => StoreWithHomeLoRoute,
  } as any)
const StoreWithHomeLoActivesIdRoute =
  StoreWithHomeLoActivesIdRouteImport.update({
    id: '/actives_/$id',
    path: '/actives/$id',
    getParentRoute: () => StoreWithHomeLoRoute,
  } as any)
const DashStoreOrdersIdSettleRoute = DashStoreOrdersIdSettleRouteImport.update({
  id: '/orders_/$id/settle',
  path: '/orders/$id/settle',
  getParentRoute: () => DashStoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$store': typeof StoreWithHomeLoRouteWithChildren
  '/dash': typeof DashRouteWithChildren
  '/my-riichi': typeof MyRiichiRouteWithChildren
  '/ready': typeof ReadyRouteWithChildren
  '/t': typeof TRouteWithChildren
  '/dash/$store': typeof DashStoreRouteWithChildren
  '/my-riichi/$id': typeof MyRiichiIdRoute
  '/ready/$code': typeof ReadyCodeRoute
  '/t/$code': typeof TCodeRoute
  '/dash/': typeof DashIndexRoute
  '/$store/actives': typeof StoreWithHomeLoActivesRoute
  '/$store/contact-us': typeof StoreWithHomeLoContactUsRoute
  '/$store/diceshock-agents': typeof StoreWithHomeLoDiceshockAgentsRoute
  '/$store/external-redirect': typeof StoreWithHomeLoExternalRedirectRoute
  '/$store/inventory': typeof StoreWithHomeLoInventoryRoute
  '/$store/me': typeof StoreWithHomeLoMeRoute
  '/$store/riichi': typeof StoreWithHomeLoRiichiRoute
  '/dash/$store/actives': typeof DashStoreActivesRoute
  '/dash/$store/events': typeof DashStoreEventsRoute
  '/dash/$store/gsz': typeof DashStoreGszRoute
  '/dash/$store/media': typeof DashStoreMediaRoute
  '/dash/$store/orders': typeof DashStoreOrdersRoute
  '/dash/$store/pricing': typeof DashStorePricingRoute
  '/dash/$store/tables': typeof DashStoreTablesRoute
  '/dash/$store/users': typeof DashStoreUsersRoute
  '/$store/': typeof StoreWithHomeLoIndexRoute
  '/dash/$store/': typeof DashStoreIndexRoute
  '/$store/actives/$id': typeof StoreWithHomeLoActivesIdRoute
  '/$store/actives/new': typeof StoreWithHomeLoActivesNewRoute
  '/$store/events/$id': typeof StoreWithHomeLoEventsIdRoute
  '/$store/inventory/$id': typeof StoreWithHomeLoInventoryIdRoute
  '/dash/$store/actives/$id': typeof DashStoreActivesIdRoute
  '/dash/$store/events/$id': typeof DashStoreEventsIdRoute
  '/dash/$store/gsz/$id': typeof DashStoreGszIdRoute
  '/dash/$store/orders/settle': typeof DashStoreOrdersSettleRoute
  '/dash/$store/pricing/$id': typeof DashStorePricingIdRoute
  '/dash/$store/tables/$id': typeof DashStoreTablesIdRoute
  '/dash/$store/users/$id': typeof DashStoreUsersIdRoute
  '/dash/$store/orders/$id/settle': typeof DashStoreOrdersIdSettleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$store': typeof StoreWithHomeLoIndexRoute
  '/my-riichi': typeof MyRiichiRouteWithChildren
  '/ready': typeof ReadyRouteWithChildren
  '/t': typeof TRouteWithChildren
  '/my-riichi/$id': typeof MyRiichiIdRoute
  '/ready/$code': typeof ReadyCodeRoute
  '/t/$code': typeof TCodeRoute
  '/dash': typeof DashIndexRoute
  '/$store/actives': typeof StoreWithHomeLoActivesRoute
  '/$store/contact-us': typeof StoreWithHomeLoContactUsRoute
  '/$store/diceshock-agents': typeof StoreWithHomeLoDiceshockAgentsRoute
  '/$store/external-redirect': typeof StoreWithHomeLoExternalRedirectRoute
  '/$store/inventory': typeof StoreWithHomeLoInventoryRoute
  '/$store/me': typeof StoreWithHomeLoMeRoute
  '/$store/riichi': typeof StoreWithHomeLoRiichiRoute
  '/dash/$store/actives': typeof DashStoreActivesRoute
  '/dash/$store/events': typeof DashStoreEventsRoute
  '/dash/$store/gsz': typeof DashStoreGszRoute
  '/dash/$store/media': typeof DashStoreMediaRoute
  '/dash/$store/orders': typeof DashStoreOrdersRoute
  '/dash/$store/pricing': typeof DashStorePricingRoute
  '/dash/$store/tables': typeof DashStoreTablesRoute
  '/dash/$store/users': typeof DashStoreUsersRoute
  '/dash/$store': typeof DashStoreIndexRoute
  '/$store/actives/$id': typeof StoreWithHomeLoActivesIdRoute
  '/$store/actives/new': typeof StoreWithHomeLoActivesNewRoute
  '/$store/events/$id': typeof StoreWithHomeLoEventsIdRoute
  '/$store/inventory/$id': typeof StoreWithHomeLoInventoryIdRoute
  '/dash/$store/actives/$id': typeof DashStoreActivesIdRoute
  '/dash/$store/events/$id': typeof DashStoreEventsIdRoute
  '/dash/$store/gsz/$id': typeof DashStoreGszIdRoute
  '/dash/$store/orders/settle': typeof DashStoreOrdersSettleRoute
  '/dash/$store/pricing/$id': typeof DashStorePricingIdRoute
  '/dash/$store/tables/$id': typeof DashStoreTablesIdRoute
  '/dash/$store/users/$id': typeof DashStoreUsersIdRoute
  '/dash/$store/orders/$id/settle': typeof DashStoreOrdersIdSettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$store': typeof StoreRouteWithChildren
  '/dash': typeof DashRouteWithChildren
  '/my-riichi': typeof MyRiichiRouteWithChildren
  '/ready': typeof ReadyRouteWithChildren
  '/t': typeof TRouteWithChildren
  '/$store/_with-home-lo': typeof StoreWithHomeLoRouteWithChildren
  '/dash/$store': typeof DashStoreRouteWithChildren
  '/my-riichi/$id': typeof MyRiichiIdRoute
  '/ready/$code': typeof ReadyCodeRoute
  '/t/$code': typeof TCodeRoute
  '/dash/': typeof DashIndexRoute
  '/$store/_with-home-lo/actives': typeof StoreWithHomeLoActivesRoute
  '/$store/_with-home-lo/contact-us': typeof StoreWithHomeLoContactUsRoute
  '/$store/_with-home-lo/diceshock-agents': typeof StoreWithHomeLoDiceshockAgentsRoute
  '/$store/_with-home-lo/external-redirect': typeof StoreWithHomeLoExternalRedirectRoute
  '/$store/_with-home-lo/inventory': typeof StoreWithHomeLoInventoryRoute
  '/$store/_with-home-lo/me': typeof StoreWithHomeLoMeRoute
  '/$store/_with-home-lo/riichi': typeof StoreWithHomeLoRiichiRoute
  '/dash/$store/actives': typeof DashStoreActivesRoute
  '/dash/$store/events': typeof DashStoreEventsRoute
  '/dash/$store/gsz': typeof DashStoreGszRoute
  '/dash/$store/media': typeof DashStoreMediaRoute
  '/dash/$store/orders': typeof DashStoreOrdersRoute
  '/dash/$store/pricing': typeof DashStorePricingRoute
  '/dash/$store/tables': typeof DashStoreTablesRoute
  '/dash/$store/users': typeof DashStoreUsersRoute
  '/$store/_with-home-lo/': typeof StoreWithHomeLoIndexRoute
  '/dash/$store/': typeof DashStoreIndexRoute
  '/$store/_with-home-lo/actives_/$id': typeof StoreWithHomeLoActivesIdRoute
  '/$store/_with-home-lo/actives_/new': typeof StoreWithHomeLoActivesNewRoute
  '/$store/_with-home-lo/events_/$id': typeof StoreWithHomeLoEventsIdRoute
  '/$store/_with-home-lo/inventory_/$id': typeof StoreWithHomeLoInventoryIdRoute
  '/dash/$store/actives_/$id': typeof DashStoreActivesIdRoute
  '/dash/$store/events_/$id': typeof DashStoreEventsIdRoute
  '/dash/$store/gsz_/$id': typeof DashStoreGszIdRoute
  '/dash/$store/orders_/settle': typeof DashStoreOrdersSettleRoute
  '/dash/$store/pricing_/$id': typeof DashStorePricingIdRoute
  '/dash/$store/tables_/$id': typeof DashStoreTablesIdRoute
  '/dash/$store/users_/$id': typeof DashStoreUsersIdRoute
  '/dash/$store/orders_/$id/settle': typeof DashStoreOrdersIdSettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$store'
    | '/dash'
    | '/my-riichi'
    | '/ready'
    | '/t'
    | '/dash/$store'
    | '/my-riichi/$id'
    | '/ready/$code'
    | '/t/$code'
    | '/dash/'
    | '/$store/actives'
    | '/$store/contact-us'
    | '/$store/diceshock-agents'
    | '/$store/external-redirect'
    | '/$store/inventory'
    | '/$store/me'
    | '/$store/riichi'
    | '/dash/$store/actives'
    | '/dash/$store/events'
    | '/dash/$store/gsz'
    | '/dash/$store/media'
    | '/dash/$store/orders'
    | '/dash/$store/pricing'
    | '/dash/$store/tables'
    | '/dash/$store/users'
    | '/$store/'
    | '/dash/$store/'
    | '/$store/actives/$id'
    | '/$store/actives/new'
    | '/$store/events/$id'
    | '/$store/inventory/$id'
    | '/dash/$store/actives/$id'
    | '/dash/$store/events/$id'
    | '/dash/$store/gsz/$id'
    | '/dash/$store/orders/settle'
    | '/dash/$store/pricing/$id'
    | '/dash/$store/tables/$id'
    | '/dash/$store/users/$id'
    | '/dash/$store/orders/$id/settle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$store'
    | '/my-riichi'
    | '/ready'
    | '/t'
    | '/my-riichi/$id'
    | '/ready/$code'
    | '/t/$code'
    | '/dash'
    | '/$store/actives'
    | '/$store/contact-us'
    | '/$store/diceshock-agents'
    | '/$store/external-redirect'
    | '/$store/inventory'
    | '/$store/me'
    | '/$store/riichi'
    | '/dash/$store/actives'
    | '/dash/$store/events'
    | '/dash/$store/gsz'
    | '/dash/$store/media'
    | '/dash/$store/orders'
    | '/dash/$store/pricing'
    | '/dash/$store/tables'
    | '/dash/$store/users'
    | '/dash/$store'
    | '/$store/actives/$id'
    | '/$store/actives/new'
    | '/$store/events/$id'
    | '/$store/inventory/$id'
    | '/dash/$store/actives/$id'
    | '/dash/$store/events/$id'
    | '/dash/$store/gsz/$id'
    | '/dash/$store/orders/settle'
    | '/dash/$store/pricing/$id'
    | '/dash/$store/tables/$id'
    | '/dash/$store/users/$id'
    | '/dash/$store/orders/$id/settle'
  id:
    | '__root__'
    | '/'
    | '/$store'
    | '/dash'
    | '/my-riichi'
    | '/ready'
    | '/t'
    | '/$store/_with-home-lo'
    | '/dash/$store'
    | '/my-riichi/$id'
    | '/ready/$code'
    | '/t/$code'
    | '/dash/'
    | '/$store/_with-home-lo/actives'
    | '/$store/_with-home-lo/contact-us'
    | '/$store/_with-home-lo/diceshock-agents'
    | '/$store/_with-home-lo/external-redirect'
    | '/$store/_with-home-lo/inventory'
    | '/$store/_with-home-lo/me'
    | '/$store/_with-home-lo/riichi'
    | '/dash/$store/actives'
    | '/dash/$store/events'
    | '/dash/$store/gsz'
    | '/dash/$store/media'
    | '/dash/$store/orders'
    | '/dash/$store/pricing'
    | '/dash/$store/tables'
    | '/dash/$store/users'
    | '/$store/_with-home-lo/'
    | '/dash/$store/'
    | '/$store/_with-home-lo/actives_/$id'
    | '/$store/_with-home-lo/actives_/new'
    | '/$store/_with-home-lo/events_/$id'
    | '/$store/_with-home-lo/inventory_/$id'
    | '/dash/$store/actives_/$id'
    | '/dash/$store/events_/$id'
    | '/dash/$store/gsz_/$id'
    | '/dash/$store/orders_/settle'
    | '/dash/$store/pricing_/$id'
    | '/dash/$store/tables_/$id'
    | '/dash/$store/users_/$id'
    | '/dash/$store/orders_/$id/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRoute: typeof StoreRouteWithChildren
  DashRoute: typeof DashRouteWithChildren
  MyRiichiRoute: typeof MyRiichiRouteWithChildren
  ReadyRoute: typeof ReadyRouteWithChildren
  TRoute: typeof TRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/t': {
      id: '/t'
      path: '/t'
      fullPath: '/t'
      preLoaderRoute: typeof TRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-riichi': {
      id: '/my-riichi'
      path: '/my-riichi'
      fullPath: '/my-riichi'
      preLoaderRoute: typeof MyRiichiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$store': {
      id: '/$store'
      path: '/$store'
      fullPath: '/$store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof TRoute
    }
    '/ready/$code': {
      id: '/ready/$code'
      path: '/$code'
      fullPath: '/ready/$code'
      preLoaderRoute: typeof ReadyCodeRouteImport
      parentRoute: typeof ReadyRoute
    }
    '/my-riichi/$id': {
      id: '/my-riichi/$id'
      path: '/$id'
      fullPath: '/my-riichi/$id'
      preLoaderRoute: typeof MyRiichiIdRouteImport
      parentRoute: typeof MyRiichiRoute
    }
    '/dash/$store': {
      id: '/dash/$store'
      path: '/$store'
      fullPath: '/dash/$store'
      preLoaderRoute: typeof DashStoreRouteImport
      parentRoute: typeof DashRoute
    }
    '/$store/_with-home-lo': {
      id: '/$store/_with-home-lo'
      path: ''
      fullPath: '/$store'
      preLoaderRoute: typeof StoreWithHomeLoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/dash/$store/': {
      id: '/dash/$store/'
      path: '/'
      fullPath: '/dash/$store/'
      preLoaderRoute: typeof DashStoreIndexRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/$store/_with-home-lo/': {
      id: '/$store/_with-home-lo/'
      path: '/'
      fullPath: '/$store/'
      preLoaderRoute: typeof StoreWithHomeLoIndexRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/dash/$store/users': {
      id: '/dash/$store/users'
      path: '/users'
      fullPath: '/dash/$store/users'
      preLoaderRoute: typeof DashStoreUsersRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/tables': {
      id: '/dash/$store/tables'
      path: '/tables'
      fullPath: '/dash/$store/tables'
      preLoaderRoute: typeof DashStoreTablesRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/pricing': {
      id: '/dash/$store/pricing'
      path: '/pricing'
      fullPath: '/dash/$store/pricing'
      preLoaderRoute: typeof DashStorePricingRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/orders': {
      id: '/dash/$store/orders'
      path: '/orders'
      fullPath: '/dash/$store/orders'
      preLoaderRoute: typeof DashStoreOrdersRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/media': {
      id: '/dash/$store/media'
      path: '/media'
      fullPath: '/dash/$store/media'
      preLoaderRoute: typeof DashStoreMediaRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/gsz': {
      id: '/dash/$store/gsz'
      path: '/gsz'
      fullPath: '/dash/$store/gsz'
      preLoaderRoute: typeof DashStoreGszRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/events': {
      id: '/dash/$store/events'
      path: '/events'
      fullPath: '/dash/$store/events'
      preLoaderRoute: typeof DashStoreEventsRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/actives': {
      id: '/dash/$store/actives'
      path: '/actives'
      fullPath: '/dash/$store/actives'
      preLoaderRoute: typeof DashStoreActivesRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/$store/_with-home-lo/riichi': {
      id: '/$store/_with-home-lo/riichi'
      path: '/riichi'
      fullPath: '/$store/riichi'
      preLoaderRoute: typeof StoreWithHomeLoRiichiRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/me': {
      id: '/$store/_with-home-lo/me'
      path: '/me'
      fullPath: '/$store/me'
      preLoaderRoute: typeof StoreWithHomeLoMeRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/inventory': {
      id: '/$store/_with-home-lo/inventory'
      path: '/inventory'
      fullPath: '/$store/inventory'
      preLoaderRoute: typeof StoreWithHomeLoInventoryRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/external-redirect': {
      id: '/$store/_with-home-lo/external-redirect'
      path: '/external-redirect'
      fullPath: '/$store/external-redirect'
      preLoaderRoute: typeof StoreWithHomeLoExternalRedirectRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/diceshock-agents': {
      id: '/$store/_with-home-lo/diceshock-agents'
      path: '/diceshock-agents'
      fullPath: '/$store/diceshock-agents'
      preLoaderRoute: typeof StoreWithHomeLoDiceshockAgentsRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/contact-us': {
      id: '/$store/_with-home-lo/contact-us'
      path: '/contact-us'
      fullPath: '/$store/contact-us'
      preLoaderRoute: typeof StoreWithHomeLoContactUsRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/actives': {
      id: '/$store/_with-home-lo/actives'
      path: '/actives'
      fullPath: '/$store/actives'
      preLoaderRoute: typeof StoreWithHomeLoActivesRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/dash/$store/users_/$id': {
      id: '/dash/$store/users_/$id'
      path: '/users/$id'
      fullPath: '/dash/$store/users/$id'
      preLoaderRoute: typeof DashStoreUsersIdRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/tables_/$id': {
      id: '/dash/$store/tables_/$id'
      path: '/tables/$id'
      fullPath: '/dash/$store/tables/$id'
      preLoaderRoute: typeof DashStoreTablesIdRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/pricing_/$id': {
      id: '/dash/$store/pricing_/$id'
      path: '/pricing/$id'
      fullPath: '/dash/$store/pricing/$id'
      preLoaderRoute: typeof DashStorePricingIdRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/orders_/settle': {
      id: '/dash/$store/orders_/settle'
      path: '/orders/settle'
      fullPath: '/dash/$store/orders/settle'
      preLoaderRoute: typeof DashStoreOrdersSettleRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/gsz_/$id': {
      id: '/dash/$store/gsz_/$id'
      path: '/gsz/$id'
      fullPath: '/dash/$store/gsz/$id'
      preLoaderRoute: typeof DashStoreGszIdRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/events_/$id': {
      id: '/dash/$store/events_/$id'
      path: '/events/$id'
      fullPath: '/dash/$store/events/$id'
      preLoaderRoute: typeof DashStoreEventsIdRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/dash/$store/actives_/$id': {
      id: '/dash/$store/actives_/$id'
      path: '/actives/$id'
      fullPath: '/dash/$store/actives/$id'
      preLoaderRoute: typeof DashStoreActivesIdRouteImport
      parentRoute: typeof DashStoreRoute
    }
    '/$store/_with-home-lo/inventory_/$id': {
      id: '/$store/_with-home-lo/inventory_/$id'
      path: '/inventory/$id'
      fullPath: '/$store/inventory/$id'
      preLoaderRoute: typeof StoreWithHomeLoInventoryIdRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/events_/$id': {
      id: '/$store/_with-home-lo/events_/$id'
      path: '/events/$id'
      fullPath: '/$store/events/$id'
      preLoaderRoute: typeof StoreWithHomeLoEventsIdRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/actives_/new': {
      id: '/$store/_with-home-lo/actives_/new'
      path: '/actives/new'
      fullPath: '/$store/actives/new'
      preLoaderRoute: typeof StoreWithHomeLoActivesNewRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/$store/_with-home-lo/actives_/$id': {
      id: '/$store/_with-home-lo/actives_/$id'
      path: '/actives/$id'
      fullPath: '/$store/actives/$id'
      preLoaderRoute: typeof StoreWithHomeLoActivesIdRouteImport
      parentRoute: typeof StoreWithHomeLoRoute
    }
    '/dash/$store/orders_/$id/settle': {
      id: '/dash/$store/orders_/$id/settle'
      path: '/orders/$id/settle'
      fullPath: '/dash/$store/orders/$id/settle'
      preLoaderRoute: typeof DashStoreOrdersIdSettleRouteImport
      parentRoute: typeof DashStoreRoute
    }
  }
}

interface StoreWithHomeLoRouteChildren {
  StoreWithHomeLoActivesRoute: typeof StoreWithHomeLoActivesRoute
  StoreWithHomeLoContactUsRoute: typeof StoreWithHomeLoContactUsRoute
  StoreWithHomeLoDiceshockAgentsRoute: typeof StoreWithHomeLoDiceshockAgentsRoute
  StoreWithHomeLoExternalRedirectRoute: typeof StoreWithHomeLoExternalRedirectRoute
  StoreWithHomeLoInventoryRoute: typeof StoreWithHomeLoInventoryRoute
  StoreWithHomeLoMeRoute: typeof StoreWithHomeLoMeRoute
  StoreWithHomeLoRiichiRoute: typeof StoreWithHomeLoRiichiRoute
  StoreWithHomeLoIndexRoute: typeof StoreWithHomeLoIndexRoute
  StoreWithHomeLoActivesIdRoute: typeof StoreWithHomeLoActivesIdRoute
  StoreWithHomeLoActivesNewRoute: typeof StoreWithHomeLoActivesNewRoute
  StoreWithHomeLoEventsIdRoute: typeof StoreWithHomeLoEventsIdRoute
  StoreWithHomeLoInventoryIdRoute: typeof StoreWithHomeLoInventoryIdRoute
}

const StoreWithHomeLoRouteChildren: StoreWithHomeLoRouteChildren = {
  StoreWithHomeLoActivesRoute: StoreWithHomeLoActivesRoute,
  StoreWithHomeLoContactUsRoute: StoreWithHomeLoContactUsRoute,
  StoreWithHomeLoDiceshockAgentsRoute: StoreWithHomeLoDiceshockAgentsRoute,
  StoreWithHomeLoExternalRedirectRoute: StoreWithHomeLoExternalRedirectRoute,
  StoreWithHomeLoInventoryRoute: StoreWithHomeLoInventoryRoute,
  StoreWithHomeLoMeRoute: StoreWithHomeLoMeRoute,
  StoreWithHomeLoRiichiRoute: StoreWithHomeLoRiichiRoute,
  StoreWithHomeLoIndexRoute: StoreWithHomeLoIndexRoute,
  StoreWithHomeLoActivesIdRoute: StoreWithHomeLoActivesIdRoute,
  StoreWithHomeLoActivesNewRoute: StoreWithHomeLoActivesNewRoute,
  StoreWithHomeLoEventsIdRoute: StoreWithHomeLoEventsIdRoute,
  StoreWithHomeLoInventoryIdRoute: StoreWithHomeLoInventoryIdRoute,
}

const StoreWithHomeLoRouteWithChildren = StoreWithHomeLoRoute._addFileChildren(
  StoreWithHomeLoRouteChildren,
)

interface StoreRouteChildren {
  StoreWithHomeLoRoute: typeof StoreWithHomeLoRouteWithChildren
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreWithHomeLoRoute: StoreWithHomeLoRouteWithChildren,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface DashStoreRouteChildren {
  DashStoreActivesRoute: typeof DashStoreActivesRoute
  DashStoreEventsRoute: typeof DashStoreEventsRoute
  DashStoreGszRoute: typeof DashStoreGszRoute
  DashStoreMediaRoute: typeof DashStoreMediaRoute
  DashStoreOrdersRoute: typeof DashStoreOrdersRoute
  DashStorePricingRoute: typeof DashStorePricingRoute
  DashStoreTablesRoute: typeof DashStoreTablesRoute
  DashStoreUsersRoute: typeof DashStoreUsersRoute
  DashStoreIndexRoute: typeof DashStoreIndexRoute
  DashStoreActivesIdRoute: typeof DashStoreActivesIdRoute
  DashStoreEventsIdRoute: typeof DashStoreEventsIdRoute
  DashStoreGszIdRoute: typeof DashStoreGszIdRoute
  DashStoreOrdersSettleRoute: typeof DashStoreOrdersSettleRoute
  DashStorePricingIdRoute: typeof DashStorePricingIdRoute
  DashStoreTablesIdRoute: typeof DashStoreTablesIdRoute
  DashStoreUsersIdRoute: typeof DashStoreUsersIdRoute
  DashStoreOrdersIdSettleRoute: typeof DashStoreOrdersIdSettleRoute
}

const DashStoreRouteChildren: DashStoreRouteChildren = {
  DashStoreActivesRoute: DashStoreActivesRoute,
  DashStoreEventsRoute: DashStoreEventsRoute,
  DashStoreGszRoute: DashStoreGszRoute,
  DashStoreMediaRoute: DashStoreMediaRoute,
  DashStoreOrdersRoute: DashStoreOrdersRoute,
  DashStorePricingRoute: DashStorePricingRoute,
  DashStoreTablesRoute: DashStoreTablesRoute,
  DashStoreUsersRoute: DashStoreUsersRoute,
  DashStoreIndexRoute: DashStoreIndexRoute,
  DashStoreActivesIdRoute: DashStoreActivesIdRoute,
  DashStoreEventsIdRoute: DashStoreEventsIdRoute,
  DashStoreGszIdRoute: DashStoreGszIdRoute,
  DashStoreOrdersSettleRoute: DashStoreOrdersSettleRoute,
  DashStorePricingIdRoute: DashStorePricingIdRoute,
  DashStoreTablesIdRoute: DashStoreTablesIdRoute,
  DashStoreUsersIdRoute: DashStoreUsersIdRoute,
  DashStoreOrdersIdSettleRoute: DashStoreOrdersIdSettleRoute,
}

const DashStoreRouteWithChildren = DashStoreRoute._addFileChildren(
  DashStoreRouteChildren,
)

interface DashRouteChildren {
  DashStoreRoute: typeof DashStoreRouteWithChildren
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashStoreRoute: DashStoreRouteWithChildren,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface MyRiichiRouteChildren {
  MyRiichiIdRoute: typeof MyRiichiIdRoute
}

const MyRiichiRouteChildren: MyRiichiRouteChildren = {
  MyRiichiIdRoute: MyRiichiIdRoute,
}

const MyRiichiRouteWithChildren = MyRiichiRoute._addFileChildren(
  MyRiichiRouteChildren,
)

interface ReadyRouteChildren {
  ReadyCodeRoute: typeof ReadyCodeRoute
}

const ReadyRouteChildren: ReadyRouteChildren = {
  ReadyCodeRoute: ReadyCodeRoute,
}

const ReadyRouteWithChildren = ReadyRoute._addFileChildren(ReadyRouteChildren)

interface TRouteChildren {
  TCodeRoute: typeof TCodeRoute
}

const TRouteChildren: TRouteChildren = {
  TCodeRoute: TCodeRoute,
}

const TRouteWithChildren = TRoute._addFileChildren(TRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRouteWithChildren,
  DashRoute: DashRouteWithChildren,
  MyRiichiRoute: MyRiichiRouteWithChildren,
  ReadyRoute: ReadyRouteWithChildren,
  TRoute: TRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
