// biome-ignore-all lint: gen

/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routers/__root'
import { Route as WithHomeLoRouteImport } from './routers/_with-home-lo'

const DashLazyRouteImport = createFileRoute('/dash')()
const DashGraphiqlLazyRouteImport = createFileRoute('/dash/graphiql')()

const DashLazyRoute = DashLazyRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routers/dash.lazy').then((d) => d.Route))
const WithHomeLoRoute = WithHomeLoRouteImport.update({
  id: '/_with-home-lo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashGraphiqlLazyRoute = DashGraphiqlLazyRouteImport.update({
  id: '/graphiql',
  path: '/graphiql',
  getParentRoute: () => DashLazyRoute,
} as any).lazy(() =>
  import('./routers/dash/graphiql.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/dash': typeof DashLazyRouteWithChildren
  '/dash/graphiql': typeof DashGraphiqlLazyRoute
}
export interface FileRoutesByTo {
  '/dash': typeof DashLazyRouteWithChildren
  '/dash/graphiql': typeof DashGraphiqlLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_with-home-lo': typeof WithHomeLoRoute
  '/dash': typeof DashLazyRouteWithChildren
  '/dash/graphiql': typeof DashGraphiqlLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dash' | '/dash/graphiql'
  fileRoutesByTo: FileRoutesByTo
  to: '/dash' | '/dash/graphiql'
  id: '__root__' | '/_with-home-lo' | '/dash' | '/dash/graphiql'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithHomeLoRoute: typeof WithHomeLoRoute
  DashLazyRoute: typeof DashLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-home-lo': {
      id: '/_with-home-lo'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithHomeLoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/graphiql': {
      id: '/dash/graphiql'
      path: '/graphiql'
      fullPath: '/dash/graphiql'
      preLoaderRoute: typeof DashGraphiqlLazyRouteImport
      parentRoute: typeof DashLazyRoute
    }
  }
}

interface DashLazyRouteChildren {
  DashGraphiqlLazyRoute: typeof DashGraphiqlLazyRoute
}

const DashLazyRouteChildren: DashLazyRouteChildren = {
  DashGraphiqlLazyRoute: DashGraphiqlLazyRoute,
}

const DashLazyRouteWithChildren = DashLazyRoute._addFileChildren(
  DashLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WithHomeLoRoute: WithHomeLoRoute,
  DashLazyRoute: DashLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
