// biome-ignore-all lint: gen

/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routers/__root'
import { Route as WithHomeLoRouteImport } from './routers/_with-home-lo'

const DashLazyRouteImport = createFileRoute('/dash')()

const DashLazyRoute = DashLazyRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routers/dash.lazy').then((d) => d.Route))
const WithHomeLoRoute = WithHomeLoRouteImport.update({
  id: '/_with-home-lo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dash': typeof DashLazyRoute
}
export interface FileRoutesByTo {
  '/dash': typeof DashLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_with-home-lo': typeof WithHomeLoRoute
  '/dash': typeof DashLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dash'
  fileRoutesByTo: FileRoutesByTo
  to: '/dash'
  id: '__root__' | '/_with-home-lo' | '/dash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithHomeLoRoute: typeof WithHomeLoRoute
  DashLazyRoute: typeof DashLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-home-lo': {
      id: '/_with-home-lo'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithHomeLoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WithHomeLoRoute: WithHomeLoRoute,
  DashLazyRoute: DashLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
